version: "2.4"
services:
  cuda:
    image: pddg/sel-gpu-debug-container:9.2
    container_name: cuda92
    volumes:
      - /mnt:/mnt:rw
      - /am/home/roundgoby:/am/home/roundgoby:rw
      - /etc/nslcd.conf:/etc/nslcd.conf:ro
    runtime: nvidia
    restart: always
