version: "2.4"
services:
  cuda:
    image: pddg/sel-gpu-debug-container:9.2
    container_name: cuda92
    volumes:
      - /mnt:/mnt:rw
      - /am/home/zacco:/am/home/zacco:rw
      - /etc/nslcd.conf:/etc/nslcd.conf:ro
      - /etc/ldap.conf:/etc/ldap.conf
    runtime: nvidia
    restart: always
