version: "2.4"
services:
  cuda92:
    extends:
      file: docker-compose.base.yml
      service: cuda
    image: pddg/sel-gpu-debug-container:9.2
    container_name: cuda92
    ports:
      - "22092:22"
  cuda100:
    extends:
      file: docker-compose.base.yml
      service: cuda
    image: pddg/sel-gpu-debug-container:10.0
    container_name: cuda100
    ports:
      - "22100:22"
  cuda101:
    extends:
      file: docker-compose.base.yml
      service: cuda
    image: pddg/sel-gpu-debug-container:10.1
    container_name: cuda101
    ports:
      - "22101:22"

networks:
  defaults:
    external:
      name: gpu-net
